# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"load_data": "ETL_Pipeline_Preparation.ipynb",
         "clean_data": "ETL_Pipeline_Preparation.ipynb",
         "get_engine": "ETL_Pipeline_Preparation.ipynb",
         "save_data": "ETL_Pipeline_Preparation.ipynb"}

modules = ["process_data.py"]

doc_url = "https://rickatx.github.io/message_response_pipeline/"

git_url = "https://github.com/rickatx/message_response_pipeline/tree/master/"

def custom_doc_links(name): return None
